### PR TITLE
feat: remove support for deprecated mongodb version 4.4 and add 6.0 support

### PR DESCRIPTION
**Pull request by Aashiq-J**
### Description

While adding the ICD versions test, I found that 4.4 has been deprecated. Hence creating this PR to add support for the new stable version 6.0

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content
drop support for mongodb version 4.4 and add support for mongodb version 6

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by rajatagarwal-ibm** [comment]
@Aashiq-J can you add a URL for supporting versions in the variables.tf description?

**Comment by rajatagarwal-ibm** [comment]
Check commit convention - https://www.conventionalcommits.org/en/v1.0.0/ 

You could use `"feat:...` if you are creating a feature.

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
