### PR TITLE
feat: added support to restore DB from backup id

### PR DESCRIPTION
**Pull request by Ak-sky**
### Description

Added support to restore DB from backup id.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

Added support to restore DB from backup id.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by Ak-sky** [comment]
- Able to restore mongodb instance from the backup id-

   image

- Restored instance details- 

   image

**Comment by Ak-sky** [comment]
Upgrade Test is failing-

> TestRunCompleteUpgradeExample 2024-03-13T05:49:57Z command.go:185: ╵
> TestRunCompleteUpgradeExample 2024-03-13T05:49:57Z retry.go:99: Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1; ╷
> Error: [0m Error: [ERROR] Error getting database config while updating adminpassword for: crn:v1:bluemix:public:databases-for-mongodb:eu-de:a/abac0df06b644a9cabc6e44f55b3880e:99e990ab-df83-4ca3-8fa7-9884140d6203:: with error Internal Server Error
> │ 
> │   with module.mongodb.ibm_database.mongodb,
> │   on ../../main.tf line 49, in resource "ibm_database" "mongodb":
> │   49: resource "ibm_database" "mongodb" {
> │ 
> ╵}
>     tests.go:365: 
>         	Error Trace:	/go/pkg/mod/github.com/terraform-ibm-modules/ibmcloud-terratest-wrapper@v1.29.6/testhelper/tests.go:365
>         	            				/go/pkg/mod/github.com/terraform-ibm-modules/ibmcloud-terratest-wrapper@v1.29.6/testhelper/tests.go:682
>         	            				/__w/terraform-ibm-icd-mongodb/terraform-ibm-icd-mongodb/tests/pr_test.go:110
>         	Error:      	Received unexpected error:
>         	            	FatalError{Underlying: error while running command: exit status 1; ╷
> Error:  	            	│ Error: [ERROR] Error getting database config while updating adminpassword for: crn:v1:bluemix:public:databases-for-mongodb:eu-de:a/abac0df06b644a9cabc6e44f55b3880e:99e990ab-df83-4ca3-8fa7-9884140d6203:: with error Internal Server Error
>         	            	│ 
>         	            	│   with module.mongodb.ibm_database.mongodb,
>         	            	│   on ../../main.tf line 49, in resource "ibm_database" "mongodb":
>         	            	│   49: resource "ibm_database" "mongodb" {
>         	            	│ 
>         	            	╵}
>         	Test:       	TestRunCompleteUpgradeExample
> TestRunCompleteUpgradeExample 2024-03-13T05:49:57Z tests.go:366: FatalError{Underlying: error while running command: exit status 1; ╷
> Error: [0m Error: [ERROR] Error getting database config while updating adminpassword for: crn:v1:bluemix:public:databases-for-mongodb:eu-de:a/abac0df06b644a9cabc6e44f55b3880e:99e990ab-df83-4ca3-8fa7-9884140d6203:: with error Internal Server Error
> │ 
> │   with module.mongodb.ibm_database.mongodb,

**Review by rajatagarwal-ibm — APPROVED** [review]

**Pull request merged**
