### PR TITLE
tests: Added backup restore from backup id example

### PR DESCRIPTION
**Pull request by Ak-sky**
### Description

Added backup restore from backup id example

### Release required?

- [x] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by Ak-sky** [comment]
Test is failing due to this issue- https://github.com/IBM-Cloud/terraform-provider-ibm/issues/5263

**Comment by Ak-sky** [comment]
Test failed due to the know provider [issue](https://github.ibm.com/GoldenEye/issues/issues/7304)- 

```
TestRunCompleteUpgradeExample 2024-04-25T09:25:56Z logger.go:66: │ Error: Provider produced inconsistent result after apply
TestRunCompleteUpgradeExample 2024-04-25T09:25:56Z logger.go:66: │ 
TestRunCompleteUpgradeExample 2024-04-25T09:25:56Z logger.go:66: │ When applying changes to module.cbr_zone.ibm_cbr_zone.cbr_zone, provider
TestRunCompleteUpgradeExample 2024-04-25T09:25:56Z logger.go:66: │ "provider[\"registry.terraform.io/ibm-cloud/ibm\"]" produced an unexpected
TestRunCompleteUpgradeExample 2024-04-25T09:25:56Z logger.go:66: │ new value: Root resource was present, but now absent.
TestRunCompleteUpgradeExample 2024-04-25T09:25:56Z logger.go:66: │ 
TestRunCompleteUpgradeExample 2024-04-25T09:25:56Z logger.go:66: │ This is a bug in the provider, which should be reported in the provider's
TestRunCompleteUpgradeExample 2024-04-25T09:25:56Z logger.go:66: │ own issue tracker.
TestRunCompleteUpgradeExample 2024-04-25T09:25:56Z logger.go:66: ╵
TestRunCompleteUpgradeExample 2024-04-25T09:25:56Z retry.go:144: 'terraform [apply -input=false -auto-approve -var users=[{"type" = "database", "name" = "testuser", "password" = "A1tjxo4KZfZbEZD"}] -var prefix=mongodb-upg-l6iwfa -var region=eu-de -var resource_group=geretain-test-mongo -var resource_tags=[] -var admin_pass=A1tjxo4KZfZbEZD -var mongodb_version=5.0 -lock=false]' failed with the error 'error while running command: exit status 1; ╷
```

**Comment by Ak-sky** [comment]
Test failed due to the know provider CBR [issue](https://github.ibm.com/GoldenEye/issues/issues/7304)- 

```
TestRunCompleteUpgradeExample 2024-04-25T09:25:56Z logger.go:66: │ Error: Provider produced inconsistent result after apply
TestRunCompleteUpgradeExample 2024-04-25T09:25:56Z logger.go:66: │ 
TestRunCompleteUpgradeExample 2024-04-25T09:25:56Z logger.go:66: │ When applying changes to module.cbr_zone.ibm_cbr_zone.cbr_zone, provider
TestRunCompleteUpgradeExample 2024-04-25T09:25:56Z logger.go:66: │ "provider[\"registry.terraform.io/ibm-cloud/ibm\"]" produced an unexpected
TestRunCompleteUpgradeExample 2024-04-25T09:25:56Z logger.go:66: │ new value: Root resource was present, but now absent.
TestRunCompleteUpgradeExample 2024-04-25T09:25:56Z logger.go:66: │ 
TestRunCompleteUpgradeExample 2024-04-25T09:25:56Z logger.go:66: │ This is a bug in the provider, which should be reported in the provider's
TestRunCompleteUpgradeExample 2024-04-25T09:25:56Z logger.go:66: │ own issue tracker.
TestRunCompleteUpgradeExample 2024-04-25T09:25:56Z logger.go:66: ╵
TestRunCompleteUpgradeExample 2024-04-25T09:25:56Z retry.go:144: 'terraform [apply -input=false -auto-approve -var users=[{"type" = "database", "name" = "testuser", "password" = "A1tjxo4KZfZbEZD"}] -var prefix=mongodb-upg-l6iwfa -var region=eu-de -var resource_group=geretain-test-mongo -var resource_tags=[] -var admin_pass=A1tjxo4KZfZbEZD -var mongodb_version=5.0 -lock=false]' failed with the error 'error while running command: exit status 1; ╷
```

**Review by rajatagarwal-ibm — APPROVED** [review]

**Pull request merged**
